### ISSUE TITLE
Readme.md is missing

### ISSUE THREAD

**Issue by criticalbh** [criticalbh/material2-admin#2]
Project is missing documentation on how to start, install, deploy and similar. This is angular-cli project, so basic guidelines such as cloning, dependency installation and build are enough.

**Comment by michaelsavchuk** [comment]
@criticalbh I'll have a go at it in a bit :)

**Comment by criticalbh** [comment]
@Pixelrobin sure, thanks :)

**Comment by sameerkumar18** [comment]
#3

**Comment by michaelsavchuk** [comment]
@criticalbh It seems that you removed this default information in your [latest commit](https://github.com/criticalbh/material2-admin/commit/4da505475133fbb9a82c339c7609ac53bae0ea99#diff-04c6e90faac2675aa89e2176d2eec7d8). Is there any reason for that? Do you want your information on ng to be different?

Edit, oh I see, there is no information on cloning and dep installing. I'll do that :)

**Comment by criticalbh** [comment]
@Pixelrobin , this one was auto-generated by angular-cli and I did not want to keep it there because how to scaffold and similar can be found on CLI official page, what I should have left is development and build steps.

**Comment by michaelsavchuk** [comment]
https://github.com/criticalbh/material2-admin/pull/4 Let me know if it's sufficiant.

**Comment by criticalbh** [comment]
@Pixelrobin thanks, thats it :).
